### ISSUE TITLE
Gradle 2.3.20 support

### ISSUE THREAD

**Issue by mtpdog** [XilinJia/krdb#29]
### How frequently does the bug occur?

Always

### Description

It seems that Gradle 2.3.20 requires some additional tweak: 
```
java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.fir.declarations.FirSimpleFunction org.jetbrains.kotlin.fir.plugin.SimpleFunctionBuildingContextKt.createMemberFunction(org.jetbrains.kotlin.fir.extensions.FirExtension, org.jetbrains.kotlin.fir.symbols.impl.FirClassSymbol, org.jetbrains.kotlin.GeneratedDeclarationKey, org.jetbrains.kotlin.name.Name, org.jetbrains.kotlin.fir.types.ConeKotlinType, kotlin.jvm.functions.Function1)'
```

Can you look at it?

### Stacktrace & log output

```shell

```

### Can you reproduce the bug?

Always

### Version

-

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

Yes

### Platform OS and version(s)

-

**Comment by XilinJia** [comment]
You mean, you used the latest krdb, changed kotlin to 2.3.20, built your app,  and that failed?  That's understandable.  krdb needs to be built with 2.3.20, which is what I started trying, and it appears to run fine, for now.

**Comment by klp5mu** [comment]
I can confirm that release 3.3.3 is working perfectly on our end with Kotlin v2.3.20. Thank you very much, @XilinJia we truly appreciate your efforts.

**Comment by XilinJia** [comment]
@klp5mu on what platform do you use krdb?

**Comment by klp5mu** [comment]
@XilinJia 

Build Environment:
-  macOS 26.3.1 (Dev)
-  Ubuntu 22 and 24 (CI: GitHub ubuntu-latest)
-  Java/JDK 17
-  Gradle 9.1.0
-  Android Gradle Plugin 8.13.2

Target Platform:
-  Android API 26 – 36
